# cluster-config.yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: a2a-production-cluster
  region: us-west-2

nodeGroups:
  - name: ng-1
    instanceType: t3.medium
    desiredCapacity: 3
    minSize: 1
    maxSize: 10
    availabilityZones: ["us-west-2a", "us-west-2b", "us-west-2c"]
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        albIngress: true

addons:
  - name: vpc-cni
  - name: coredns
  - name: kube-proxy
